CSS  - Add video responsive class and Geotrek video on Homepage
makinacorpus/Geotrek-website pull request #47
Opened 2021-11-06 13:15 UTC by camillemonchicourt

- I added a ``video-responsive`` CSS class. Not sure I put it in the right file ?
- I applied it to existing videos in articles.
- I added the Geotrek presentation video on Homepage (with EN subtitles by default on EN and ES versions as we only have EN subtitles available actually) and applied the CSS class to this video.

2021-11-08 14:51 UTC, numahell requested changes
> Not sure I put it in the right file ?

It is the correct file : this CSS class can be used everywhere in the website, not only in news

2021-11-08 14:51 UTC, numahell commented on assets/css/components/_layout.scss
> +.video-responsive iframe {
Sass is used, this could be simplified by using nested properties

2021-11-08 14:56 UTC, camillemonchicourt commented on assets/css/components/_layout.scss
> +.video-responsive iframe {
Hum, don't know what nested properties are. But I will try to find.

2021-11-11 20:31 UTC, camillemonchicourt commented on assets/css/components/_layout.scss
> +.video-responsive iframe {
OK @numahell, I think it did it with the nested way now.

2021-11-29 14:26 UTC, numahell commented on assets/css/components/_layout.scss
> +.video-responsive iframe {
Yeah it does ! sorry I should have give you doc page from sass.

2021-11-29 14:26 UTC, numahell approved these changes

2021-11-29 14:33 UTC, merged

2021-11-29 14:37 UTC, camillemonchicourt commented
OK thanks, it is not working properly on mobile : https://geotrek.fr while it was OK in my tests... 🤔
Same here : https://geotrek.fr/2021/11/04/geotrek-rencontres-2021-synthese.html

2021-11-29 14:41 UTC, camillemonchicourt commented
It is working properly in the news, was just my cache...
Something seems to be wrong with the video on homepage, I will check.