Add new articles and new module Geotrek-rando-widget in products's page
makinacorpus/Geotrek-website pull request #63
Opened 2024-05-06 06:26 UTC by bruhnild

2024-05-06 08:32 UTC, babastienne requested changes
Sur les noms des briques, j'aimerai qu'on arrive à rendre le tout plus homogène, et qu'on conserve la syntaxe suivante : 
- Geotrek-admin
- Geotrek-rando
- Geotrek-mobile
- Geotrek-widget (et pas Geotrek rando widget)

sur les articles : peux-tu modifier les dates des articles suivants pour espacer un peu leur publication ? 
- Open Source : 01/24
- Ecosystème : 02/24
- Outdoor : 03/24
- Widget : 05/24
- on ne change rien pour l'article sur les pages statiques

Peux-tu montrer avec une capture d'écran ce que ça rend dans l'interface la nouvelle page produit ?

Ah, et dans les articles pense à ajouter une balise `<!--more-->` pour indiquer l'endroit où la résumé de l'article doit d'arrêter, sinon sur [la page d'articles](https://geotrek.fr/actualites.html) on aura tout l'article de visible plutôt que son introduction.

2024-05-06 09:20 UTC, camillemonchicourt commented on _posts/2024-04-16-the-power-of-community-and-open-source-how-geotrek-endures-over-time.markdown
> +<p><strong>Geotrek existe depuis plus de 10 ans mais reste toujours l'outil le plus plébiscité par les Parcs et les territoires naturels pour gérer et promouvoir les activités outdoor !</strong> Aujo
```suggestion
<p><strong>Geotrek existe depuis plus de 10 ans mais reste toujours l'outil le plus plébiscité par les Parcs et les espaces naturels pour gérer et promouvoir les activités de pleine nature !</strong> Aujourd'hui, découvrons le monde de l'open source et comment Geotrek a relevé le défi de perdurer grâce à l'engagement de sa communauté.</p>
```

2024-05-06 09:20 UTC, camillemonchicourt commented on _posts/2024-04-16-the-power-of-community-and-open-source-how-geotrek-endures-over-time.markdown
> +<p><strong>Qu'est-ce que la Communauté Open Source ?</strong> <strong>La communauté Open Source est une collaboration dynamique de contributeurs volontaires partageant une passion commune pour le dév
```suggestion
<p><strong>Qu'est-ce que la Communauté Open Source ?</strong> <strong>La communauté Open Source est une collaboration dynamique de contributeurs volontaires et de structures partageant une passion commune pour le développement de logiciels libres et la volonté de faire évoluer le projet collectivement. C'est un écosystème où la transparence, la collaboration et l'innovation sont au cœur de chaque projet !</strong></p>
```

2024-05-06 09:20 UTC, camillemonchicourt commented on _posts/2024-04-16-the-power-of-community-and-open-source-how-geotrek-endures-over-time.markdown
> +<p><strong>Merci à tous les contributeurs qui rendent cette aventure possible !</strong><br>&nbsp;</p>
```suggestion
<p><strong>Merci à tous les contributeurs qui rendent cette aventure possible depuis plus de 10 ans !</strong><br></p>
```

2024-05-06 09:20 UTC, camillemonchicourt commented on _posts/2024-04-23-ecosytem-geotrek.markdown
> +<p><b>Et si on vous disait que saisir une seule fois une randonnée pour qu’elle puisse ensuite être diffusée sur Cirkwi, IGN Rando, APIDAE, VisoRando ou encore OutdoorActive c’est possible ?&nbsp;<br
```suggestion
<p><b>Et si on vous disait que saisir une seule fois une randonnée pour qu’elle puisse ensuite être diffusée sur Cirkwi, IGNrando', Apidae, Visorando ou encore Outdooractive c’est possible ?<br>Bienvenue dans l’écosystème Geotrek !</b>
```

2024-05-06 09:20 UTC, camillemonchicourt commented on _posts/2024-04-23-ecosytem-geotrek.markdown
> +    <li>Cirkwi</li>
```suggestion
    <li>IGNrando'</li>
    <li>Cirkwi</li>
    <li>Visorando</li>
    <li>Outdooractive</li>
```

2024-05-06 09:20 UTC, camillemonchicourt commented on _posts/2024-04-23-ecosytem-geotrek.markdown
> +    <li>QGIS</li>
QGIS et ArcGIS ne sont pas des plateformes, mais des outils, on n'y synchronise pas des données. A supprimer, sinon il faut aussi mettre R, Word, Calc, Excel, Bloc note, etc etc..

2024-05-06 09:20 UTC, camillemonchicourt commented on _posts/2024-04-23-ecosytem-geotrek.markdown
> +<p><b>Geotrek est la solution pour interconnecter tout un écosystème d’outils liés au monde des activités de pleines nature.</b></p>
```suggestion
<p><b>Geotrek est la solution pour interconnecter tout un écosystème d’outils liés au monde des activités de pleine nature.</b></p>
```

2024-05-06 09:20 UTC, camillemonchicourt commented on _posts/2024-04-26-manage-and-enhance-outdoor-activities-with-outdoor-module.markdown
> +    <li><a target="_blank" rel="noopener noreferrer" href="https://geotrek.readthedocs.io/en/2.104.2/usage/touristic-modules.html#activites-outdoor"><b>Documentation du module</b></a>&nbsp;</li>
```suggestion
    <li><a target="_blank" rel="noopener noreferrer" href="https://geotrek.readthedocs.io/en/latest/usage/touristic-modules.html#activites-outdoor"><b>Documentation du module</b></a>&nbsp;</li>
```

2024-05-06 09:20 UTC, camillemonchicourt commented on _posts/2024-05-02-new-on-geotrek-widget.markdown
> +<p>Plus léger et plus facile à installer que Geotrek-Rando, le widget est la solution idéale pour les territoires ayant déjà un site internet et souhaitant simplement valoriser dessus des contenus is
```suggestion
<p>Le widget est une solution simple pour les territoires ayant déjà un site internet et souhaitant y valoriser des contenus issus de Geotrek sans déployer un site dédié.</p>
```

2024-05-06 09:20 UTC, camillemonchicourt commented on _posts/2024-05-02-new-on-geotrek-widget.markdown
> +<p><strong>Grâce aux financements des Parcs Naturels Régionaux du Haut-Jura et Loire Anjou Touraine, Geotrek est maintenant en capacité de proposer un widget enrichi en fonctionnalités, conçues pour
```suggestion
<p><strong>Grâce aux financements des Parcs Naturels Régionaux du Haut-Jura et Loire Anjou Touraine, Geotrek est maintenant en capacité de proposer un widget enrichi en fonctionnalités, conçues pour maximiser la visibilité de vos activités de plein air.</strong></p>
```

2024-05-06 09:20 UTC, camillemonchicourt commented on _posts/2024-05-02-new-on-geotrek-widget.markdown
> +<p><strong>1. Cartographie interactive</strong> : transformez votre site en une expérience immersive avec une cartographie interactive, permettant à vos visiteurs de visualiser et de planifier des it
```suggestion
<p><strong>1. Cartographie interactive</strong> : transformez votre site en une expérience immersive avec une cartographie interactive, permettant à vos visiteurs de visualiser et de planifier des itinéraires en un clin d'œil.<br><strong>2. Informations détaillées</strong> : fournissez des détails complets sur les itinéraires, y compris la distance, le dénivelé, la difficulté, les points d'intérêt et bien plus encore, pour offrir une expérience informative à vos utilisateurs. Sur toute fiche il est possible en un clic de télécharger la fiche PDF de l’objet ou encore sa trace GPX.<br><strong>3. Personnalisation avancée</strong> : adaptez le widget à l'esthétique de votre site grâce à des options de personnalisation avancées, assurant une intégration harmonieuse avec votre charte graphique et votre marque.<br><strong>4. Sensibilisation des visiteurs</strong>&nbsp;: grâce aux modules Zones sensibles synchronisé avec Biodiv’Sport ou encore via le module POI, informez vos visiteurs des zones de sensibilité environnementale et participez activement à l’essor d’un tourisme plus responsable.<br><strong>5. Interface adaptée aux smartphones</strong> : pensé et structuré pour être « mobile first », le widget garantit une navigation intuitive. Le widget a été développé pour être facilement intégrable sur tous les sites web de votre choix afin de diffuser vos contenus au plus grand nombre.</p>
```

2024-05-06 09:20 UTC, camillemonchicourt commented on _posts/2024-05-02-new-on-geotrek-widget.markdown
> +    <li>Ajout de nouvelles configuration et simplification du déploiement</li>
```suggestion
    <li>Ajout de nouvelles configurations et simplification du déploiement</li>
```

2024-05-06 09:20 UTC, camillemonchicourt commented on _posts/2024-05-04-new-on-flatpages.markdown
> +<div>Le CCTP du projet a été partagé sur <a target="_blank" rel="noopener noreferrer" href="https://geotrek.ecrins-parcnational.fr/ressources/cctp/2023-10-CCTP-PNE-Destination-PNE-Pages-statiques.pdf
```suggestion
<div>Le cahier des charges du projet a été partagé sur <a target="_blank" rel="noopener noreferrer" href="https://geotrek.ecrins-parcnational.fr/ressources/cctp/2023-10-CCTP-PNE-Destination-PNE-Pages-statiques.pdf">https://geotrek.ecrins-parcnational.fr/ressources/cctp/2023-10-CCTP-PNE-Destination-PNE-Pages-statiques.pdf</a> et la consultation a été remportée par Makina Corpus.</div>
```

2024-05-06 09:20 UTC, camillemonchicourt commented on assets/img/screen-1.png
Ces images sont très grandes et font plusieurs Mo inutilement, il me semble.

2024-05-06 09:20 UTC, camillemonchicourt commented on produit.html
> +            <a href="https://sidobre-vallees-tourisme.com/type_activite/balades-et-randonnees-sidobre-vallees/" class="button button--small button--jaune" target="_blank">Version d'essai</a>
```suggestion
            <a href="https://sidobre-vallees-tourisme.com/type_activite/balades-et-randonnees-sidobre-vallees/" class="button button--small button--jaune" target="_blank">Exemple d'utilisation</a>
```

2024-05-13 06:37 UTC, bruhnild commented
Voici la homepage de la page produits. J'ai essayé de bricoler un logo dans le même esprit que les 3 autres pour le widget mais je peux en mettre en un autre.

![image](https://github.com/GeotrekCE/Geotrek-website/assets/26433045/65164c66-e245-425c-a879-1c7ec66cd7a4)

Voici la description du widget dans la page Produits :

![image](https://github.com/GeotrekCE/Geotrek-website/assets/26433045/72ce0d98-3a79-425d-8357-cc2134f28be2)

J'ai également harmonisé les appelations des modules et inclus le widget dans les solutions désormais 4 en 1 (le contenu peut être changé si besoin)  :

![image](https://github.com/GeotrekCE/Geotrek-website/assets/26433045/8a385e31-80ca-4b73-aeb6-9f1223c25e75)

J'ai ajouté les logos des structures suivantes dans la page A propos et changé les titres : 

CD30
PNR Livradois Forez
CD61
CD62
CD66

![image](https://github.com/GeotrekCE/Geotrek-website/assets/26433045/de925e34-53cb-4b3d-81fc-c5a460d9da6d)

Pour finir, j'ai modifié la date des articles comme demandé et ajouté la balise <!--more--> aux articles dans la page Actualités pour n'afficher que l'introduction :

![image](https://github.com/GeotrekCE/Geotrek-website/assets/26433045/deab666f-07e8-44b8-9c8b-d5b66b9cdbbf)

2024-05-13 08:37 UTC, babastienne commented on index.html
> +      <p>Geotrek-admin pour la gestion des données, Geotrek-rando pour la promotion des activités, Geotrek-widget pour la promotion et l'intégration d'activités sur des sites existants et Geotrek-mob
```suggestion
      <p>Geotrek-admin pour la gestion des données, Geotrek-rando pour la promotion des activités, Geotrek-widget pour intégrer la valorisation d'activités sur un site existant et Geotrek-mobile sur le terrain constituent une offre unique et incontournable</p>
```

2024-05-13 08:37 UTC, babastienne commented on assets/img/geotrek-widget.svg
Serait-ce possible de revoir un peu le format pour se rapprocher d ce qu'il y a sur les autres : un rond jaune plus petit et excentré ?

2024-05-13 08:47 UTC, camillemonchicourt reviewed
A few additional suggestions.

2024-05-13 08:47 UTC, camillemonchicourt commented on _posts/2023-09-19-updates-on-new-features.markdown
> +Les modules disponibles sont, pour la partie gestion : les tronçons, les sentiers, les aménagements, les signalétiques, les interventions et les chantiers.
```suggestion
Les modules disponibles sont, pour la partie gestion : les tronçons, les sentiers, les aménagements, les signalétiques, les interventions et les chantiers, ainsi que les sites et parcours Outdoor. 
```
Le module OUTDOOR peut être à la fois utilisé pour la gestion et/ou la valorisation.

2024-05-13 08:47 UTC, camillemonchicourt commented on _posts/2023-09-19-updates-on-new-features.markdown
> +Les modules dont les objets seront affichés sur Geotrek-rando sont : les itinéraires, les points d'intérêts, les contenus touristiques, les événements touristiques, ainsi que les sites et parcours ou
```suggestion
Les modules dont les objets seront affichés sur Geotrek-rando sont : les itinéraires, les points d'intérêts, les contenus touristiques, les événements touristiques, ainsi que les sites et parcours outdoor (sports de pleine nature). Vous pouvez en découvrir un exemple sur [le site escapade62](https://www.escapade62.fr/) réalisé pour le département du Pas-De-Calais
```

2024-05-13 08:47 UTC, camillemonchicourt commented on _posts/2023-09-19-updates-on-new-features.markdown
> +Tous les modules de Geotrek-Admin disposent désormais d'une API, qui expose les contenus publiés pour récupération sur Geotrek-Rando et rend également ces données accessibles pour tout autre usage.
```suggestion
Tous les modules de valorisation de Geotrek-admin disposent désormais d'une API, qui expose les contenus publiés pour récupération sur Geotrek-rando et rend également ces données accessibles pour tout autre usage.
```

2024-05-13 08:47 UTC, camillemonchicourt commented on _posts/2023-09-19-updates-on-new-features.markdown
> +Un module spécifique de signalements permet aux visiteurs du site de valorisation de faire remonter des problèmes rencontrés sur leur trajets (dépôt de pollution, conflit d'usage...).
```suggestion
Un module spécifique de signalements permet aux visiteurs du site de valorisation de faire remonter des problèmes rencontrés sur leur trajet (dépôt de pollution, conflit d'usage...).
```

2024-05-13 08:47 UTC, camillemonchicourt commented on _posts/2023-09-19-updates-on-new-features.markdown
> +Un site peut regrouper plusieurs parcours, et un même parcours peut également être composé de sous-parcours. Par exemple un site d'escalade peut regrouper plusieurs parcours verticaux, et au sein d'u
```suggestion
Un site peut regrouper plusieurs parcours, et un même parcours peut également être composé de sous-parcours pour l'itinérance. Par exemple un site d'escalade peut être découpé en plusieurs secteurs (sous-sites), regroupant chacun plusieurs parcours verticaux. On retrouve un exemple ici avec [la roche de Rame](https://gtr3demo.ecrins-parcnational.fr/outdoor-site/89-La-roche-de-Rame)
```
Les sous-parcours, c'est uniquement dans le cas assez particulier de l'itinérance sur les sites Outdoor.
Dans le module Outdoor, on utilise surtout la notion de sous-sites.

2024-05-13 08:47 UTC, camillemonchicourt commented on _posts/2023-09-19-updates-on-new-features.markdown
> +Les futurs développements auront pour objet d'intégrer la notion de verticalité dans Geotrek.
Ça je ne comprends pas de quoi il s'agit.
On gère déjà les activités verticales. 
On a juste ajouté ensuite les images HD, mais c'est en plus et pas forcément uniquement pour les activités verticales.

2024-05-13 08:47 UTC, camillemonchicourt commented on _posts/2023-09-19-updates-on-new-features.markdown
> +La gestion des cotations (niveaux de difficulté) a été affinée sur le module Itinéraire et sur les modules Outdoor. Il est désormais possible de définir différentes échelles de cotation, chaque échel
Ici on parle des cotations sur les itinéraires, mais on donne un exemple de cotations sur des objets Outdoor, donc c'est confusant. On peut plutôt donner l'exemple des cotations spécifiques au VTT.
Par ailleurs, les cotations ne sont justement pas forcément des niveaux de difficultés dans le module ITINERAIRES qui est un champs à part et commun à toutes les pratiques.
```suggestion
La gestion des cotations a été affinée sur le module Itinéraire sur le modèle de ce qui existait dans les modules Outdoor. Il est désormais possible de définir différentes échelles de cotation spécifique à chaque pratique sportive, en complément du niveau de difficulté. Par exemple, dans la pratique du VTT, on peut ainsi définir le niveau de technicité et le type de voie.
```

2024-05-13 08:47 UTC, camillemonchicourt commented on _posts/2023-09-19-updates-on-new-features.markdown
> +![Geotrek-admin, détail d'un site](https://makina-corpus.com/sites/default/files/2022-09/geotrek_admin_site_rocher_meyzel.png)
Est-on certain que toutes ces images ne changent pas un jour d'URL ?
Ne vaudrait-il mieux pas pointer sur des images locales, disponibles sur geotrek.fr pour garantir leur pérennité ?

2024-05-13 08:47 UTC, camillemonchicourt commented on _posts/2023-09-19-updates-on-new-features.markdown
> +Mon collègue Timothée de Montety a travaillé sur cette partie importante pour affiner les informations sur l'accessibilité des itinéraires et des contenus touristiques.
```suggestion
Un travail a aussi été réalisé pour affiner les informations sur l'accessibilité des itinéraires et des contenus touristiques.
```

2024-05-13 08:47 UTC, camillemonchicourt commented on _posts/2023-09-19-updates-on-new-features.markdown
> +Célia Prat en a parlé précédemment dans deux articles, Geotrek est désormais en capacité de faire le lien avec Suricate, et ce de deux façons possibles :
```suggestion
Geotrek est désormais en capacité de faire le lien avec Suricate, et ce de deux façons possibles :
```

2024-05-13 08:47 UTC, camillemonchicourt commented on _posts/2023-09-19-updates-on-new-features.markdown
> +- le mode Suricate Workflow, décrit [dans cet article](https://makina-corpus.com/geotrek/gestion-territoires-naturels-geotrek-traitement-signalements-suricate)
Surtout ajouter un lien vers la doc ? https://geotrek.readthedocs.io/en/latest/install/advanced-configuration.html#suricate-support

2024-05-13 08:47 UTC, camillemonchicourt commented on _posts/2023-09-19-updates-on-new-features.markdown
> +Le développement de Georivière, un outil de gestion de rivières et milieux aquatiques reposant sur les mêmes briques logicielles que Geotrek-Admin a permis le **passage à Bootstrap 4**, ainsi que la
```suggestion
Le développement de Georivière, un outil de gestion de rivières et milieux aquatiques reposant sur les mêmes briques logicielles que Geotrek-admin a permis le **passage à Bootstrap 4**, ainsi que la possibilité de consulter le site en responsive.
```

2024-05-13 08:47 UTC, camillemonchicourt commented on _posts/2023-09-19-updates-on-new-features.markdown
> +Sur la partie cartographique, tous les types d'objets sont disponibles dans la liste des couches, et donc affichables. On peut par exemple afficher en même temps les itinéraires et les interventions.
```suggestion
Sur la partie cartographique, tous les types d'objets sont désormais disponibles dans la liste des couches, et donc affichables. On peut par exemple afficher en même temps les itinéraires et les interventions.
```

2024-05-13 08:47 UTC, camillemonchicourt commented on _posts/2023-09-19-updates-on-new-features.markdown
> +Des vues ont été ajoutées à la base de données de Geotrek, et permettent de visualiser les objets via un outil tel que QGis. Marine Faucher et Timothée De Montety [détaillent dans cet article le déve
```suggestion
Des vues ont été ajoutées à la base de données de Geotrek, et permettent de visualiser les objets via un outil tel que QGIS. Marine Faucher et Timothée De Montety [détaillent dans cet article le développement et l'usage de ces vues SQL](https://makina-corpus.com/django/creer-vues-sql-django-et-afficher-dans-un-sig).
```

2024-05-13 08:47 UTC, camillemonchicourt commented on _posts/2023-09-19-updates-on-new-features.markdown
> +#### Vues SQL pour la visualisation dans QGis
```suggestion
#### Vues SQL pour la visualisation dans QGIS
```

2024-05-13 08:47 UTC, camillemonchicourt commented on _posts/2023-09-19-updates-on-new-features.markdown
> +Ce widget, utilisable et intégrable simplement sur un site tiers, permet de valoriser les contenus (ou une partie) sans avoir besoin de déployer de Geotrek-Rando. Il peut permettre de partager les do
```suggestion
Ce widget, utilisable et intégrable simplement sur un site tiers, permet de valoriser les contenus (ou une partie) sans avoir besoin de déployer l'outil Geotrek-rando. Il peut permettre de partager les données sur les sites web de partenaires territoriaux (communautés de communes, offices de tourisme, hébergements...) car ils auront la possibilité de ré-utiliser sur leur site institutionnel le contenu déjà saisi.
```

2024-05-13 08:47 UTC, camillemonchicourt commented on _posts/2023-09-19-updates-on-new-features.markdown
> +Un travail sur les performances de l'application commandé par le Parc National des Écrins a permis de repenser certaines briques logicielles pour améliorer le temps de réponse de l'application.
```suggestion
Un travail sur les performances de l'application commandé par le Parc National des Écrins a permis de repenser certaines briques logicielles pour améliorer le temps de réponse de l'application Geotrek-admin et de son API.
```

2024-05-13 08:47 UTC, camillemonchicourt commented on _posts/2023-11-13-geotrek-widget-improved-en.markdown
> +    alt="Écosystème Geotrek"
```suggestion
    alt="Widget Geotrek"
```

2024-05-13 08:47 UTC, camillemonchicourt commented on _posts/2023-11-13-widget-geotrek-evolue-fr.markdown
> +    alt="Écosystème Geotrek"
```suggestion
    alt="Widget Geotrek"
```

2024-05-13 09:58 UTC, babastienne commented
@bruhnild peux-tu aussi mettre à jour l'année / copyright dans le footer stp ?

2024-05-13 10:00 UTC, babastienne commented
@bruhnild peux-tu également dans le footer dans la section "Communauté" ajouter un lien 'Discussion instantanée' vers cette url : https://matrix.to/#/%23geotrek:matrix.org

2024-05-13 14:31 UTC, bruhnild commented
Retours intégrés dans le dernier commit. 

Ai traduit les nouveaux articles en anglais et la fiche produit de geotrek-widget en anglais et espagnol.

2024-05-13 15:14 UTC, merged